# https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
