language: node_js
node_js: 10
cache: yarn

git:
  depth: false

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ad988ee53a3a_key -iv $encrypted_ad988ee53a3a_iv -in $TRAVIS_BUILD_DIR/scripts/deploy-travis.enc -out /tmp/deploy-travis -d
  - chmod 600 /tmp/deploy-travis
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy-travis
  - echo "$DEPLOY_KNOWN_HOSTS" >> $HOME/.ssh/known_hosts
  - sed -i '/bundle.js/d' $TRAVIS_BUILD_DIR/frontend/.gitignore

jobs:
  include:
    - stage: lint
      name: "lint API"
      install: (cd api && yarn --production false)
      script: cd api && yarn lint
    - name: "lint frontend"
      install: (cd frontend && yarn --production false)
      script: cd frontend && yarn lint

    - stage: build
      name: "build API"
      install: (cd api && yarn --production false)
      script: cd api && yarn build
    - name: "build frontend"
      install: (cd frontend && yarn --production false)
      script: cd frontend && yarn build
    - name: "build extension"
      install: (cd chrome-extension && yarn --production false)
      script: cd chrome-extension && yarn build

    - stage: deploy
      name: "deploy frontend"
      install: skip
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: scripts/deploy-frontend.sh staging
          on:
            branch: dev

        - provider: script
          skip_cleanup: true
          script: scripts/deploy-frontend.sh production
          on:
            branch: master

