language: node_js
node_js: 10

cache: yarn

git:
  depth: false

env:
  global:
    - NODE_ENV="production"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ad988ee53a3a_key -iv $encrypted_ad988ee53a3a_iv -in $TRAVIS_BUILD_DIR/scripts/deploy-travis.enc -out /tmp/deploy-travis -d
  - chmod 600 /tmp/deploy-travis
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy-travis
  - echo "$DEPLOY_KNOWN_HOSTS" >> $HOME/.ssh/known_hosts

stages:
  - test
  - build

install: yarn --production false

jobs:
  include:
    - stage: test
      name: "test API"
      before_install: cd api
      script: yarn lint
    - name: "test frontend"
      before_install: cd frontend
      script: yarn lint

    - stage: build
      name: "build API"
      before_install: cd api
      script: yarn build
    - stage: build
      name: "build frontend"
      before_install: cd frontend
      before_script: source $TRAVIS_BUILD_DIR/scripts/setup-env.sh
      script: yarn build
      deploy:
        - provider: script
          script: $TRAVIS_BUILD_DIR/scripts/deploy-frontend.sh "$DEPLOY_USER_PRODUCTION@$DEPLOY_HOSTNAME" public
          on:
            branch: master
          skip_cleanup: true
        - provider: script
          script: $TRAVIS_BUILD_DIR/scripts/deploy-frontend.sh "$DEPLOY_USER_STAGING@$DEPLOY_HOSTNAME" public
          on:
            branch: dev
          skip_cleanup: true
    - name: "build extension"
      before_install: cd chrome-extension
      script: yarn build
