language: node_js
node_js: 10

cache: yarn

git:
  depth: false

env:
  global:
    - NODE_ENV="production"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ad988ee53a3a_key -iv $encrypted_ad988ee53a3a_iv -in $TRAVIS_BUILD_DIR/scripts/deploy-travis.enc -out /tmp/deploy-travis -d
  - chmod 600 /tmp/deploy-travis
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy-travis
  - echo "$DEPLOY_KNOWN_HOSTS" >> $HOME/.ssh/known_hosts

stages:
  - build
  - test
  - name: deploy
    if: ((branch = master) OR (branch = dev)) AND (NOT (type = pull_request))

install: yarn --production false

jobs:
  include:
    - stage: test
      name: "test API"
      before_install: cd api
      script: yarn lint
    - name: "test frontend"
      before_install: cd frontend
      script: yarn lint

    - stage: build
      name: "build API"
      before_install: cd api
      script: yarn build
    - stage: build
      name: "build frontend"
      before_install: cd frontend
      before_deploy:
        - git config --local user.name "cdv"
        - git config --local user.email "dev@cdv.nils.cx"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      script:
        - yarn clean
        - yarn build
      before_deploy:
        - cd public
        - zip -r $TRAVIS_BUILD_DIR/release.zip .
      deploy:
        provider: releases
        api_key:
          secure: Wl/f4YxY6G/+zMW9fZNGm2ZpANwF+UgvRNR3V7wWyrNJ00MkhJyD9rOblkBvZH1WNtRZGkKoGX/1kzP6UB7tEW8RmT9Si3927MV6YSyigFpJaTOrf1SnlLWCKI3XRPfWRWg76Oj+hcAQ8dQ5Ml5uZwcBKtePIZ78roe8+/sIuSxaccS+x47b6sT8JcUmUO53cq04O1O7gM8AXTDxLeaSjXUb97MaENoIoaEizq2ZhcnSsyJaM9yvy/V5KY6pzTDt4Rngtjr22iYN7pPKm8AgYvCg/EE7vhpcYUCm5sM7UkkoNCb1V8uOmDv3Zu35hnRVHkDc+jTy/3p3ml3MyYEO/9bk/8MLtuaSWMXCBteZhUzmF5esvYLlvqADRBzllH0Qxed894nRDEfpbPkDocYRCV4Xe8PuYVBNnZAG2yopZA9Hv4/VUuMFxyDADNAma+EcgM8iBMR20+m7v+QPgk97AgnkKDqHe1gRo67OhIILygUVIvO62ua6to4eMIbla/RXX+Z4Ye5iMybLO+jnNwwAZokHWPDW4+Fg2K/BvukVrW1n0cp/1m0TgSxrQOXd7U5iUL0qn0CxeULvvkszpGt+NfDEBbnspYkgFgLak8KUakjngr1ftO+PTGv2jdBmgQAVpPF/a8MO91UM/ieQVnUds6IK9UT6DBXOOVSO0/sv5Dg=
        file: $TRAVIS_BUILD_DIR/release.zip
        on:
          branch:
            - dev
            - master
        skip_cleanup: true
        overwrite: true
    - name: "build extension"
      before_install: cd chrome-extension
      script: yarn build

    - stage: deploy
      name: "deploy frontend"
      install: skip
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: scripts/deploy-frontend.sh ~/frontend staging
          on:
            branch: dev

        - provider: script
          skip_cleanup: true
          script: scripts/deploy-frontend.sh ~/frontend production
          on:
            branch: master
