language: node_js
node_js: 10

cache:
  yarn: true
  directories:
  - $TRAVIS_BUILD_DIR/api/node_modules
  - $TRAVIS_BUILD_DIR/frontend/node_modules
  - $TRAVIS_BUILD_DIR/frontend/public
  - $TRAVIS_BUILD_DIR/chrome-extension/node_modules

git:
  depth: false

env:
  global:
    NODE_ENV=production

install:
  - (cd api && yarn --production false)
  - (cd frontend && yarn --production false)
  - (cd chrome-extension && yarn --production false)

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ad988ee53a3a_key -iv $encrypted_ad988ee53a3a_iv -in $TRAVIS_BUILD_DIR/scripts/deploy-travis.enc -out /tmp/deploy-travis -d
  - chmod 600 /tmp/deploy-travis
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy-travis
  - echo "$DEPLOY_KNOWN_HOSTS" >> $HOME/.ssh/known_hosts

stages:
  - build
  - test
  - name: deploy
    if: ((branch = master) OR (branch = dev)) AND (NOT (type IN (push, pull_request)))

jobs:
  include:
    - stage: test
      name: "test API"
      script: cd api && yarn lint
    - name: "test frontend"
      script: cd frontend && yarn lint

    - stage: build
      name: "build API"
      script: cd api && yarn build
    - name: "build frontend"
      script: cd frontend && yarn build
      env:
        - API_URL=__ENV__API_URL__
        - BASE_URL=__ENV__BASE_URL__
        - CHROME_EXTENSION_ID=__ENV__CHROME_EXTENSION_ID__
    - name: "build extension"
      script: cd chrome-extension && yarn build

    - stage: deploy
      name: "deploy frontend"
      install: skip
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: scripts/deploy-frontend.sh staging
          on:
            branch: dev

        - provider: script
          skip_cleanup: true
          script: scripts/deploy-frontend.sh production
          on:
            branch: master
