version: '3.4'
services:

  api:
    build:
      context: ./api
      network: host

  restoredb:
    build:
      context: ./api
      network: host

  extension:
    build: ./extension

  website:
    build: ./website
    container_name: ri-website
    hostname: ri-website
    ports:
      - 8080:80
