version: '3.4'
services:

  postgresql:
    image: postgres:11.5
    container_name: zc-postgres
    hostname: zc-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db


  api:
    container_name: zc-api
    hostname: zc-api
    ports:
      - 3000:3000
    volumes:
      - ./data/avatars:/app/avatars
      - ./data/certs:/certs:ro
    command: bash -c "yarn wait-on tcp:zc-postgres:5432 && yarn db:migrate && node dist/src/main.js"
    environment:
      LISTEN_PORT: 3000
      LISTEN_IP: 0.0.0.0
      LOG_LEVEL: 'log'
      REFLECT_ORIGIN: 'true'
      ADMIN_USER: 'admin:admin@zetecom.fr:admin42'
      APP_URL: http://${LOCAL_IP:-localhost}:8000
      WEBSITE_URL: http://${LOCAL_IP:-localhost}:8080
      DB_HOST: zc-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: db
      DB_ENTITIES: ./dist/src/**/*.entity.js
      DB_MIGRATIONS: ./dist/migrations/*.js
      DB_SEEDS: ./dist/migrations/*.js
      EMAIL_HOST: domain.tld
      EMAIL_USER: username
      EMAIL_PASSWORD: password
      EMAIL_BYPASS: 'true'
      EMAIL_ACCOUNT_VERIFICATION: 'false'
      SESSION_SECRET: sekret
      SECURE_COOKIE: 'false'
      USER_AVATAR_DESTINATION: /app/avatars


  app:
    container_name: zc-app
    hostname: zc-app
    ports:
      - 8000:80
    volumes:
      - ./avatars:/var/www/avatars:ro
    environment:
      API_URL: http://${LOCAL_IP:-localhost}:3000
      WEBSITE_URL: http://${LOCAL_IP:-localhost}:8080
      GOOGLE_ANALYTICS_ID: ''
