version: '3.4'
services:

  api:
    build:
      context: ./api
      network: host

  seed:
    build:
      context: ./api
      network: host

  app:
    build: ./app

  website:
    build: ./website
    container_name: zc-website
    hostname: zc-website
    ports:
      - 8080:80
