version: '3.4'
services:

  postgresql:
    image: postgres:11.5
    container_name: zc-postgres
    hostname: zc-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db


  redis:
    image: redis
    container_name: zc-redis
    hostname: zc-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data


  api:
    container_name: zc-api
    hostname: zc-api
    ports:
      - 3000:3000
    volumes:
      - ./data/avatars:/app/avatars
      - ./data/certs:/certs:ro
    command: sh -c "
      yarn wait-on tcp:zc-postgres:5432 &&
      yarn db:migrate &&
      node src/modules/seed &&
      node src/main.js"
    environment:
      LISTEN_PORT: 3000
      LISTEN_IP: 0.0.0.0
      LOG_LEVEL: 'log'
      REFLECT_ORIGIN: 'true'
      ADMIN_USER: 'admin:admin@zetecom.fr:admin42'
      APP_URL: http://${LOCAL_IP:-localhost}:8000
      WEBSITE_URL: http://${LOCAL_IP:-localhost}:8080
      DB_HOST: zc-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: db
      DB_ENTITIES: src/**/*.entity.js
      DB_MIGRATIONS: migrations/*.js
      DB_SEEDS: seeds/*.js
      REDIS_HOST: zc-redis
      REDIS_PORT: 6379
      EMAIL_HOST: domain.tld
      EMAIL_USER: username
      EMAIL_PASSWORD: password
      EMAIL_BYPASS: 'true'
      EMAIL_ACCOUNT_VERIFICATION: 'false'
      SESSION_SECRET: sekret
      SECURE_COOKIE: 'false'
      USER_AVATAR_DESTINATION: /app/avatars


  seed:
    container_name: zc-seed
    hostname: zc-seed
    ports:
      - 4242:4242
    command: sh -c "
      yarn typeorm query 'DROP DATABASE cypress' > /dev/null 2>&1;
      DB_NAME="$DB_NAME_ROOT" yarn typeorm query 'CREATE DATABASE cypress' > /dev/null 2>&1;
      node src/modules/cypress"
    environment:
      LISTEN_PORT: 4242
      LISTEN_IP: 0.0.0.0
      DB_HOST: zc-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: cypress
      DB_NAME_ROOT: postgres
      DB_ENTITIES: src/**/*.entity.js
      DB_MIGRATIONS: migrations/*.js


  app:
    container_name: zc-app
    hostname: zc-app
    ports:
      - 8000:80
    volumes:
      - ./data/avatars:/var/www/zc-app/avatars:ro
      - ./data/avatars:/var/www/zc-app_instrumented/avatars:ro
    environment:
      API_URL: http://${LOCAL_IP:-localhost}:3000
      WEBSITE_URL: http://${LOCAL_IP:-localhost}:8080
      GOOGLE_ANALYTICS_ID: ''
