version: '3.4'
services:

  dns-proxy-server:
    image: defreitas/dns-proxy-server
    hostname: zc-dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf

  api:
    build:
      context: ./api
      network: host

  restoredb:
    build:
      context: ./api
      network: host

  app:
    build: ./app

  website:
    build: ./website
    container_name: zc-website
    hostname: zc-website
    ports:
      - 8080:80
