version: '3.4'
services:

  postgresql:
    image: postgres:11.5
    container_name: ri-postgres
    hostname: ri-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db


  api:
    container_name: ri-api
    hostname: ri-api
    ports:
      - 3000:3000
    volumes:
      - ./avatars:/app/avatars
      - ./email-templates:/app/email-templates
    command: bash -c "yarn wait-on tcp:ri-postgres:5432 && yarn start:prod"
    environment:
      NODE_ENV: production
      LISTEN_IP: 0.0.0.0
      LISTEN_PORT: 3000
      REFLECT_ORIGIN: 'true'
      EXTENSION_URL: http://localhost:8000
      WEBSITE_URL: http://localhost:8080
      DB_HOST: ri-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: db
      DB_SYNC: 'true'
      DB_ENTITIES: ./dist/src/**/*.entity.js
      DB_MIGRATIONS_DIR: ./dist/migrations/*.js
      DB_DEBUG: 'false'
      EMAIL_HOST: domain.tld
      EMAIL_USER: username
      EMAIL_PASSWORD: password
      EMAIL_BYPASS: 'true'
      EMAIL_ACCOUNT_VERIFICATION: 'false'
      EMAIL_ACCOUNT_AUTHORIZATION: 'false'
      SESSION_SECRET: sekret
      EMAIL_TEMPLATE_DIR: /app/email-templates
      USER_AVATAR_DESTINATION: /app/avatars

  restoredb:
    container_name: ri-restoredb
    hostname: ri-restoredb
    ports:
      - 4242:4242
    volumes:
      - ./api/scripts:/app/scripts
    command: bash -c "yarn start:restoredb"
    environment:
      NODE_ENV: production
      API_URL: http://ri-api:3000
      DB_HOST: ri-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: db
      DB_SYNC: 'true'
      DB_ENTITIES: ./dist/src/**/*.entity.js
      DB_MIGRATIONS_DIR: ./dist/migrations/*.js
      DB_DEBUG: 'false'


  extension:
    container_name: ri-extension
    hostname: ri-extension
    ports:
      - 8000:80
    environment:
      NODE_ENV: production
      API_URL: http://localhost:3000
      EXTENSION_URL: http://localhost:8000
      WEBSITE_URL: http://localhost:8080
      CHROME_EXTENSION_URL:
      GITHUB_REPO_URL:


  website:
    build: ./website
    container_name: ri-website
    hostname: ri-website
    ports:
      - 8080:80
