version: '3'
services:

  cypress:
    image: cypress/included:3.4.0
    container_name: ri-cypress-ci
    hostname: ri-cypress-ci
    entrypoint: bash -c "sleep 6 && cypress run --browser chrome"
    working_dir: /e2e
    volumes:
      - .:/e2e
    env:
      API_URL: http://ri-api-ci:3000
      RESTOREDB_URL: http://ri-restoredb-ci:4242
      EXTENSION_URL: http://ri-extension-ci
      WEBSITE_URL: http://ri-website-ci
