version: '3.4'
services:

  postgresql:
    environment:
      POSTGRES_DB: cypress

  api:
    command: bash -c "
      yarn wait-on tcp:zc-postgres:5432 &&
      yarn db:migrate &&
      yarn nyc --silent node dist/src/main"
    environment:
      CI: 'true'
      BYPASS_AUTHORIZATIONS: 'true'
      DB_NAME: cypress

  app:
    command: /start.sh --coverage
    environment:
      API_URL: http://localhost:3000
      GOOGLE_ANALYTICS_ID: mock
      DEBUG: 'true'
