version: '3.4'
services:

  api:
    image: nilscox/reagir-information-api:${GIT_SHA}
    environment:
      BYPASS_AUTHORIZATIONS: true

  restoredb:
    image: nilscox/reagir-information-api:${GIT_SHA}

  extension:
    image: nilscox/reagir-information-extension:${GIT_SHA}
    environment:
      API_URL: http://ri-api:3000

  cypress:
    build: ./e2e
    container_name: ri-cypress
    hostname: ri-cypress
    volumes:
      - ./e2e/cypress/screenshots:/e2e/cypress/screenshots
      - ./e2e/cypress/videos:/e2e/cypress/videos
    environment:
      CYPRESS_API_URL: http://ri-api:3000
      CYPRESS_RESTOREDB_URL: http://ri-restoredb:4242
      CYPRESS_EXTENSION_URL: http://ri-extension
      CYPRESS_WEBSITE_URL: http://ri-website
