version: '3.4'
services:

  api:
    image: nilscox/reagir-information-api:${GIT_SHA}
    command: bash -c "yarn start:coverage"
    environment:
      CI: 'true'
      BYPASS_AUTHORIZATIONS: 'true'

  restoredb:
    image: nilscox/reagir-information-api:${GIT_SHA}

  app:
    image: nilscox/reagir-information-app:${GIT_SHA}
    command: /start.sh --ci
    environment:
      API_URL: http://ri-api

  cypress:
    build: ./e2e
    container_name: ri-cypress
    hostname: ri-cypress
    volumes:
      - ./e2e/artifacts:/artifacts
      - ./coverage:/e2e/coverage
    entrypoint: bash -c "yarn wait-on http://ri-api/api/healthcheck && yarn start:ci && yarn nyc report --reporter=lcov"
    environment:
      CYPRESS_API_URL: http://ri-api
      CYPRESS_RESTOREDB_URL: http://ri-restoredb
      CYPRESS_APP_URL: http://ri-app
      CYPRESS_WEBSITE_URL: http://ri-website
