version: '3.4'
services:

  api:
    image: nilscox/reagir-information-api:${GIT_SHA}

  restoredb:
    image: nilscox/reagir-information-api:${GIT_SHA}

  app:
    image: nilscox/reagir-information-app:${GIT_SHA}
