version: '3.4'
services:

  api:
    command: bash -c "yarn wait-on tcp:zc-postgres:5432 && yarn typeorm migration:run && yarn start:coverage"
    environment:
      CI: 'true'
      BYPASS_AUTHORIZATIONS: 'true'
      DB_SYNC: 'false'
      DB_ENTITIES: ./src/**/*.entity.ts
      DB_MIGRATIONS_DIR: ./migrations/*.ts

  app:
    command: /start.sh
    environment:
      API_URL: http://localhost:3000
      CYPRESS: 'true'
      DEBUG: 'true'
