name: Build & e2e

on: [push]

jobs:

  api:
    name: build api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: api

  frontend:
    name: build frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: frontend

  e2e:
    name: end-to-end tests
    runs-on: ubuntu-latest
    needs: [api, frontend]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - run: git checkout $(echo '${{ github.ref }}' | sed 's|.*/||')
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm i -g yarn
    - run: yarn install --production=false
      working-directory: ./e2e
    - run: yarn start:ci
      working-directory: ./e2e
