name: build

on: [push]

jobs:

  api:
    name: build api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-api:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: api

  extension:
    name: build extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-extension:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: extension

  e2e:
    name: end-to-end tests
    runs-on: ubuntu-latest
    needs: [api, extension]
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --abort-on-container-exit
      working-directory: ./e2e
      env:
        GIT_SHA: ${{ github.sha }}
