name: build

on: [push]

env:
  API_IMAGE: nilscox/reagir-information-api

jobs:

  api:
    name: build api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-api:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: api

  publish-staging:
    name: publish docker image staging
    runs-on: ubuntu-latest
    needs: api
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull $API_IMAGE:${{ github.sha }}
      - run: docker tag $API_IMAGE:${{ github.sha }} $API_IMAGE:dev
      - run: docker push $API_IMAGE:dev

  publish-production:
    name: publish docker image production
    runs-on: ubuntu-latest
    needs: api
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull $API_IMAGE:${{ github.sha }}
      - run: docker tag $API_IMAGE:${{ github.sha }} $API_IMAGE:master
      - run: docker push $API_IMAGE:master

  extension:
    name: build extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-extension:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: extension

  e2e:
    name: end-to-end tests
    runs-on: ubuntu-latest
    needs: [api, extension]
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --abort-on-container-exit
      working-directory: ./e2e
      env:
        GIT_SHA: ${{ github.sha }}
