name: build

on: [push]

env:
  API_IMAGE: nilscox/reagir-information-api
  APP_IMAGE: nilscox/reagir-information-app

jobs:

  api:
    name: build api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11.5'
        postgresql db: 'test'
        postgresql user: 'root'
        postgresql password: 'root'
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-api:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: api
        buildoptions: --network=host

  app:
    name: build app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-app:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: app

  extension:
    name: build extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn && yarn build
      working-directory: ./extension

  website:
    name: build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker build .
      working-directory: ./website

  e2e:
    name: end-to-end tests
    runs-on: ubuntu-latest
    needs: [api, app, website]
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose -f ../docker-compose.yml -f docker-compose.ci.yml up --abort-on-container-exit
      working-directory: ./e2e
      env:
        GIT_SHA: ${{ github.sha }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-outputs
        path: e2e/artifacts

  publish-api-staging:
    name: publish api docker image staging
    runs-on: ubuntu-latest
    needs: [api, e2e]
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull $API_IMAGE:${{ github.sha }}
      - run: docker tag $API_IMAGE:${{ github.sha }} $API_IMAGE:dev
      - run: docker push $API_IMAGE:dev

  publish-api-production:
    name: publish api docker image production
    runs-on: ubuntu-latest
    needs: [api, e2e]
    if: github.ref == 'refs/heads/master'
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull $API_IMAGE:${{ github.sha }}
      - run: docker tag $API_IMAGE:${{ github.sha }} $API_IMAGE:master
      - run: docker push $API_IMAGE:master

  publish-app-staging:
    name: publish app docker image staging
    runs-on: ubuntu-latest
    needs: [app, e2e]
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull $APP_IMAGE:${{ github.sha }}
      - run: docker tag $APP_IMAGE:${{ github.sha }} $APP_IMAGE:dev
      - run: docker push $APP_IMAGE:dev

  publish-app-production:
    name: publish app docker image production
    runs-on: ubuntu-latest
    needs: [app, e2e]
    if: github.ref == 'refs/heads/master'
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull $APP_IMAGE:${{ github.sha }}
      - run: docker tag $APP_IMAGE:${{ github.sha }} $APP_IMAGE:master
      - run: docker push $APP_IMAGE:master
