name: Build Frontend

on: [push]

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nilscox/reagir-information-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: frontend
